blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
#    prefix: /login
    prefix: /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /connect
#    prefix:   /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
#    prefix:   /redirect
#    prefix:   /login
    prefix: /connect

google_login:
    path: /connect/check-google

facebook_login:
    path: /connect/check-facebook

github_login:
    path: /connect/check-github