blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

## FOSUserBundle routes
#fos_user_security:
#  resource: "@FOSUserBundle/Resources/config/routing/security.xml"
#
#fos_user_profile:
#  resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#  prefix: /profile
#
#fos_user_register:
#  resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#  prefix: /register
#
#fos_user_resetting:
#  resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#  prefix: /resetting
#
#fos_user_change_password:
#  resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#  prefix: /profile

admin:
  resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
  prefix: /admin

#HWIOAuthBundle routes
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
#    prefix: /login
    prefix: /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix: /connect
#    prefix:   /login

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
#    prefix:   /redirect
#    prefix:   /login
    prefix: /connect

google_login:
    path: /connect/check-google

facebook_login:
    path: /connect/check-facebook

github_login:
    path: /connect/check-github