# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

        Blogger\BlogBundle\Entity\User:
            algorithm: sha512
            encode-as-base64: true
            iterations: 10

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        main:
            entity: { class: BlogBundle:User, property: username }
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username

        oauth.user_provider:
            id: hwi_auth.oauth_user_provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
#            pattern: /.*
            pattern: ^/
            anonymous: ~
            security: true
            form_login:
                check_path: /login_check
                login_path: /login
#                login_path: fos_user_security_login
#                check_path: fos_user_security_check
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /

            logout: true

# This is the HWIOAuthBundle part
            oauth:
                resource_owners:
                    google:   "/connect/check-google"
                    facebook: "/connect/check-facebook"
                    github:   "/connect/check-github"
                login_path:     /connect
                failure_path:   /connect

                oauth_user_provider:
                    service: my_user_provider
#                    service: hwi_oauth.user.provider.fosub_bridge
#                    service: hwi_auth.oauth_user_provider


    access_control:
#        - { path: ^/$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: /admin/.*, role: ROLE_ADMIN }
        - { path: ^/blog, role: ROLE_ADMIN}
        - { path: ^/profile, role: ROLE_USER }