parameters:
    my_user_provider.class: Blogger\BlogBundle\Security\Core\User\FOSUBUserProvider

services:

    blogger_blog.twig.extension:
        class: Blogger\BlogBundle\Twig\Extensions\BloggerBlogExtension
        tags:
            - { name: twig.extension }

    my_user_provider:
#        class: "%my_user_provider.class%"
        class: %my_user_provider.class%
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: ['@fos_user.user_manager',{google: google_id}]

    hwi_oauth.user.provider.entity:
        class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider