<?php

namespace Blogger\BlogBundle\Entity\Repository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLatestBlogs()
    {
        $builder = $this->createQueryBuilder('b')
            ->select('b.id', 'b.tags', 'b.created', 'b.title', 'b.author', 'b.image' , 'b.slug', 'SUBSTRING(b.blog, 1, 500) AS blog', 'COUNT(c.id) AS commentsCount')
            ->leftJoin('b.comments', 'c')
            ->addOrderBy('b.created', 'DESC') //c сортировкой по убыванию по дате создания из табл ___.created
            ->groupBy('b.id')
        ;

        return $builder->getQuery()
            ->getArrayResult();

        //example from the article on Habrahabr (it is working)
        
//        $qb = $this->createQueryBuilder('b')
//            ->select('b, c')
//            ->leftJoin('b.comments', 'c')
//            ->addOrderBy('b.created', 'DESC');
//
//        if (false === is_null($limit))
//            $qb->setMaxResults($limit);
//
//        return $qb->getQuery()
//            ->getResult();
    }

//    public function updateBlog($newArr)
//    {
//        $qb = $this->createQueryBuilder('b');
//        $qb->update()
//            ->set('b', ':newArr')
//            ->setParameter('newArr', $newArr);
//
//        return $qb->getQuery()->execute();
//    }
    
    public function getTags()
    {
        $blogTags = $this->createQueryBuilder('b')
            ->select('b.tags')
            ->getQuery()
            ->getResult();

        $tags = array();
        foreach ($blogTags as $blogTag)
        {
            $tags = array_merge(explode(",", $blogTag['tags']), $tags);
        }

        foreach ($tags as &$tag)
        {
            $tag = trim($tag);
        }

        return $tags;
    }

    public function getTagWeights($tags)
    {
        $tagWeights = array();
        if (empty($tags))
            return $tagWeights;

        foreach ($tags as $tag)
        {
            $tagWeights[$tag] = (isset($tagWeights[$tag])) ? $tagWeights[$tag] + 1 : 1;
        }
        // Shuffle the tags
        uksort($tagWeights, function() {
            return rand() > rand();
        });

        $max = max($tagWeights);

        // Max of 5 weights
        $multiplier = ($max > 5) ? 5 / $max : 1;
        foreach ($tagWeights as &$tag)
        {
            $tag = ceil($tag * $multiplier);
        }

        return $tagWeights;
    }

}